var $ = require('jquery');
global.jQuery = $;
//var bootstrap = require('bootstrap-sass');
require("./init.js");
require("./menu-icon.js");
require("./user-img.js");
require("./time.js");
require("./form.js");
require("./like.js");
//require("./time-elapsed.js");
